name: Windows Build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        uses: ./.github/actions/prepare_environment
        with:
          target_os: windows
          is_self_hosted: false

      - name: Build warp-oss
        shell: pwsh
        run: cargo build --bin warp-oss --features gui --release --locked
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload warp-oss.exe
        uses: actions/upload-artifact@v4
        with:
          name: warp-oss-windows
          path: target/release/warp-oss.exe
